// Public browser-side names are generated from Rust-owned
// Draft Console HTTP DTOs. Keep this file as the stable import surface.
export { CONTRACT_VERSIONS, CONSOLE_NAVIGATION } from "./generated-contracts";
export type {
  ActionInputField,
  ActionInputKind,
  ActionPresentation,
  ActionTarget,
  ActionTargetKind,
  ApiResponse,
  ApiFailure,
  CanonicalRevisions,
  ConsoleNavigationSection,
  ConsoleReadModel,
  NextSafeAction,
  SelectOption,
  CapabilityGap,
  ChangeDerivationGap,
  ChangePackView,
  ClassificationBundle,
  DiscoveredExtensionDto,
  ExtensionCatalogSourceStatusDto,
  InboxItem,
  ChangePackSummary,
  ProjectSummary,
  RegistryProject,
  Resource,
  ResourceChange,
  ResourceContent,
  ResourceInterference,
  ResourceLocator,
  ReviewUnit,
  RollbackOutcome,
  RollbackUncertainty,
  SearchResult,
  VerificationCheckResult,
  ServiceJob,
  Session,
  TaskDefinition,
  TaskView,
  WorkspaceRevision,
} from "./generated-contracts";
