// @generated by cargo run -p draft-ipc --bin generate-console-contracts
// Do not edit by hand.

export const CONTRACT_VERSIONS = { apiEnvelope: 1, apiFailure: 1, mutationRequest: 1, session: 1, serviceJob: 1 } as const;

export type ApiResponse<T> = { schema_version: 1, data: T };

export type Session = { schema_version: 1, authenticated: boolean, csrf_token: string, preselected_workspace_id: string | null, };

export type WorkspaceRevision = { schema_version: 1, workspace_id: string, content_digest: string, };

export type RegistryProject = { schema_version: 1, workspace_id: string, name: string, repository_path: string, storage_path: string, created_at: string, last_seen_at: string, draft_version: string, health: string, location_revision: number, last_workspace_revision: string | null, };

export type AssigneeRefDto = { kind: string, id: string, };

export type TaskNextActionDto = { id: string, label: string, completed: boolean, };

export type TaskDefinition = { schema_version: 1, id: string, name: string, goal: string, status: string | null, priority: string | null, due_at: string | null, risk: string, mode: string, assignee_ref: AssigneeRefDto | null, next_actions: Array<TaskNextActionDto>, updated_at: string, };

export type TaskView = { task: TaskDefinition, health: string, review_status: string, recommended_action: string, execution_count: number, evidence_count: number, produced_packs: Array<string>, };

export type PackSummary = { pack_id: string, name: string, intent: string, submit_state: string, import_state: string | null, revision: number | string | null, valid_actions: Array<string>, };

export type InboxItem = { id: string | null, status: string, kind: string, subject_id: string, next_action: string, severity: string | null, };

export type ProjectSummary = { project: RegistryProject, revision: WorkspaceRevision, status: Record<string, unknown>, tasks: Array<TaskDefinition>, packs: Array<PackSummary>, inbox: Array<InboxItem>, };

export type EditorFile = { path: string, kind: string, protected: boolean, bytes: number, };

export type EditorFileView = { path: string, content: string, protected: boolean, workspace_hash: string | null, };

export type SearchResult = { kind: string, workspace_id: string | null, id: string | null, pack_id: string | null, title: string, subtitle: string | null, };

export type ExtensionCatalogLocationDto = { "kind": "local_directory", path: string, } | { "kind": "https", url: string, };

export type ExtensionCatalogSourceDto = { schema_version: 1, id: string, location: ExtensionCatalogLocationDto, configured_at: string, catalog_id: string | null, last_refreshed_at: string | null, last_error: string | null, };

export type ExtensionCatalogUsabilityDto = "untrusted" | "usable" | "expired" | "invalid" | "unavailable";

export type ExtensionCatalogSourceStatusDto = { source: ExtensionCatalogSourceDto, configured: boolean, trusted: boolean, usability: ExtensionCatalogUsabilityDto, root_version: number | null, cached_package_count: number, diagnostic: string | null, };

export type ExtensionCatalogTargetDto = { id: string, version: string, publisher: string, draft_api: string, artifact_path: string, length: number, sha256: string, };

export type DiscoveredExtensionDto = { source_id: string, catalog_id: string, freshness: ExtensionCatalogUsabilityDto, target: ExtensionCatalogTargetDto, };

export type ServiceJob = { schema_version: 1, id: string, kind: string, workspace_path: string, status: string, submitted_at: string, started_at: string | null, ended_at: string | null, result: unknown, error: string | null, operation_id: string | null, workspace_id: string | null, phase: string, progress_completed: number, progress_total: number | null, cancellation_requested: boolean, correlation_id: string, attempt: number, recovered_at: string | null, };

export type ApiErrorBodyDto = { code: string, message: string, details: unknown, };

export type ApiFailure = { schema_version: 1, error: ApiErrorBodyDto, };
