// @generated by cargo run -p draft-ipc --bin generate-console-contracts
// Do not edit by hand.

export const CONTRACT_VERSIONS = { apiEnvelope: 1, apiFailure: 1, mutationRequest: 1, session: 1, serviceJob: 1 } as const;

export type ApiResponse<T> = { schema_version: 1, data: T };

export type Session = { schema_version: 1, authenticated: boolean, csrf_token: string, preselected_workspace_id: string | null, };

export type WorkspaceRevision = { schema_version: 1, workspace_id: string, content_digest: string, };

export type RegistryProject = { schema_version: 1, workspace_id: string, name: string, project_path: string, storage_path: string, created_at: string, last_seen_at: string, draft_version: string, health: string, location_revision: number, last_workspace_revision: string | null, };

export type AssigneeRefDto = { kind: string, id: string, };

export type TaskNextActionDto = { id: string, label: string, completed: boolean, };

export type TaskDefinition = { schema_version: 1, id: string, name: string, goal: string, status: string | null, priority: string | null, due_at: string | null, risk: string, mode: string, assignee_ref: AssigneeRefDto | null, next_actions: Array<TaskNextActionDto>, updated_at: string, };

export type TaskView = { task: TaskDefinition, health: string, review_status: string, recommended_action: string, execution_count: number, evidence_count: number, produced_changes: Array<string>, };

export type ChangePackSummary = { change_pack_id: string, name: string, intent: string, submit_state: string, revision: number | string | null, valid_actions: Array<string>, };

export type InboxItem = { id: string | null, status: string, kind: string, subject_id: string, next_action: string, severity: string | null, };

export type ProjectSummary = { project: RegistryProject, revision: WorkspaceRevision, status: Record<string, unknown>, tasks: Array<TaskDefinition>, change_packs: Array<ChangePackSummary>, inbox: Array<InboxItem>, };

export type ResourceLocator = { scheme: string, body: string, };

export type CapabilityGap = { capability: string, resource_classes: Array<string>, reason: string, };

export type Resource = { locator: ResourceLocator, resource_id: string, 
/**
 * The intrinsic shape of the resource, when its adapter states one.
 */
form: string | null, protected: boolean, content_size: number | null, 
/**
 * **Every** class an installed extension assigns, sorted.
 *
 * A list, not one value: a resource genuinely is several things at once —
 * a text document *and* a language source — and rendering only the first
 * would discard a correct classification. Empty means nothing is installed
 * that recognizes it, which is not an error.
 */
classes: Array<string>, 
/**
 * Classes installed extensions define incompatibly, scoped to those
 * classes. Every other assignment on this resource still stands.
 */
class_collisions: Array<string>, };

export type ResourceContent = { locator: ResourceLocator, content: string, protected: boolean, workspace_hash: string | null, };

export type ClassificationBundle = { assigned: Array<string>, collisions: Array<string>, classification_digest: string, 
/**
 * Present when nothing is installed to classify anything. Distinguishes
 * "classified, and nothing matched" from "nothing can classify".
 */
gaps: Array<CapabilityGap>, };

export type VerificationCheckResult = { check_id: string, display_name: string, requirement: string, state: string, detail: string | null, reason: string, 
/**
 * The artifact that contributed this check, shown separately from the
 * decision that permitted it: trust and authorization are different facts.
 */
producer_extension_id: string, authorization_decision: string | null, };

export type ResourceInterference = { resource_id: string, relation: string, detail: string, };

export type ResourceChange = { resource_id: string, locator: ResourceLocator, 
/**
 * Neutral aspect names: `added`, `removed`, `content_changed`,
 * `metadata_changed`, `relocated`, `form_changed`, `attributes_changed`.
 */
aspects: Array<string>, before_state_digest: string | null, after_state_digest: string | null, };

export type ChangeDerivationGap = { 
/**
 * `presence_uncertain` or `absence_uncertain`.
 */
kind: string, resource_id: string, locator: ResourceLocator | null, 
/**
 * Which side of the comparison was not covered.
 */
uncovered_side: string, };

export type ReviewUnit = { unit_id: string, resource_id: string, label: string | null, 
/**
 * Contributed metric totals for this unit. The Console displays the keys
 * as given and attaches meaning to none of them.
 */
summary: Record<string, number>, };

export type ChangePackView = { change_set_digest: string, base_snapshot_digest: string, result_snapshot_digest: string, observation_context_digest: string, 
/**
 * What changed, proved.
 */
resources: Array<ResourceChange>, 
/**
 * What could not be determined. A separate field on purpose.
 */
derivation_gaps: Array<ChangeDerivationGap>, 
/**
 * Contributed review units, when a comparison capability derived any.
 * Absent means Draft knows *that* the resources changed without being
 * able to say how — a real answer, not an empty rendering.
 */
review_units: Array<ReviewUnit>, capability_gaps: Array<CapabilityGap>, };

export type RollbackUncertainty = { 
/**
 * `target_state_unknown`, `recovery_material_unavailable`,
 * `current_observation_incomplete`, `restore_verification_failed`,
 * `adapter_recovery_unavailable` or `context_incompatible`.
 */
kind: string, detail: string, };

export type RollbackOutcome = { 
/**
 * `complete`, `incomplete` or `refused`. Never rendered as "restored"
 * unless it is `complete`.
 */
outcome: string, target_snapshot_digest: string, resulting_snapshot_digest: string | null, 
/**
 * Typed causes, so a surface can say precisely why rather than
 * "rollback incomplete".
 */
uncertainties: Array<RollbackUncertainty>, 
/**
 * Domains whose target state can never be verified for this target,
 * however observable they become later.
 */
permanently_unverifiable_domains: Array<string>, };

export type SearchResult = { kind: string, workspace_id: string | null, id: string | null, change_pack_id: string | null, title: string, subtitle: string | null, };

export type ExtensionCatalogLocationDto = { "kind": "local_directory", path: string, } | { "kind": "https", url: string, };

export type ExtensionCatalogSourceDto = { schema_version: 1, id: string, location: ExtensionCatalogLocationDto, configured_at: string, catalog_id: string | null, last_refreshed_at: string | null, last_error: string | null, 
/**
 * A disabled source is not searched, refreshed or installed from. Its
 * configuration, trust and installed packages are all untouched.
 */
enabled: boolean, 
/**
 * Built-in sources come from the build's official bootstrap. They can be
 * disabled, but their trust anchor is not the user's to edit.
 */
builtin: boolean, };

export type ExtensionCatalogUsabilityDto = "untrusted" | "usable" | "expired" | "invalid" | "unavailable";

export type ExtensionCatalogSourceStatusDto = { source: ExtensionCatalogSourceDto, configured: boolean, trusted: boolean, usability: ExtensionCatalogUsabilityDto, root_version: number | null, cached_package_count: number, diagnostic: string | null, };

export type ExtensionCatalogTargetDto = { id: string, version: string, publisher: string, draft_api: string, artifact_path: string, length: number, sha256: string, };

export type DiscoveredExtensionDto = { source_id: string, catalog_id: string, freshness: ExtensionCatalogUsabilityDto, target: ExtensionCatalogTargetDto, };

export type ServiceJob = { schema_version: 1, id: string, kind: string, workspace_path: string, status: string, submitted_at: string, started_at: string | null, ended_at: string | null, result: unknown, error: string | null, operation_id: string | null, workspace_id: string | null, phase: string, progress_completed: number, progress_total: number | null, cancellation_requested: boolean, correlation_id: string, attempt: number, recovered_at: string | null, };

export type ApiErrorBodyDto = { code: string, message: string, details: unknown, };

export type ApiFailure = { schema_version: 1, error: ApiErrorBodyDto, };

export type CanonicalRevisions = { registry: number, workspace: string | null, change_pack: string | null, policy: string | null, };

export type ModelFreshness = "loading" | "fresh" | "stale" | "partial" | "unavailable";

export type ConsoleScope = "GLOBAL" | "PROJECT" | "CHANGE_PACK" | "BASELINE";

export type ConsoleSubject = { "scope": "GLOBAL", } | { "scope": "PROJECT", workspace_id: string, } | { "scope": "CHANGE_PACK", workspace_id: string, change_pack_id: string, } | { "scope": "BASELINE", workspace_id: string, baseline_id: string, };

export type SelectOption = { value: string, label: string, };

export type ActionInputKind = { "type": "text", max_length: number | null, } | { "type": "select", options: Array<SelectOption>, } | { "type": "boolean" } | { "type": "confirmation" };

export type ActionInputField = { 
/**
 * Stable machine identity: the key the client submits and the server
 * validates. Never a label.
 */
id: string, 
/**
 * Human label. Presentation only.
 */
label: string, kind: ActionInputKind, required: boolean, help: string | null, };

export type ActionTargetKind = "extension" | "extension_source" | "pending_authorization" | "grant";

export type ActionTarget = { kind: ActionTargetKind, id: string, };

export type ActionPresentation = { action_id: string, label: string, enabled: boolean, disabled_reason: string | null, invocation_capability: string | null, requires_confirmation: boolean, expires_at_unix_ms: number | null, 
/**
 * What this action needs from the caller. Empty means it takes nothing,
 * and supplying anything is then an error.
 *
 * This is one contract serving two purposes: a frontend renders it, and
 * `draftd` validates against it. The frontend's checks are a convenience;
 * the server's are the decision.
 */
inputs: Array<ActionInputField>, 
/**
 * Digest of `inputs`, carried into the invocation capability so a stale
 * input contract cannot be replayed.
 */
input_contract_digest: string, 
/**
 * What the action acts on, when it is something other than the subject.
 */
target: ActionTarget | null, };

export type NextSafeAction = { label: string, reason: string, action_id: string | null, };

export type ConsoleNavigationSection = { label: string, children: Array<string>, };

export type ConsoleReadModel = { subject: ConsoleSubject, revisions: CanonicalRevisions, freshness: ModelFreshness, health: string, read_only: boolean, permission_reason: string | null, navigation: Array<ConsoleNavigationSection>, content: unknown, actions: Array<ActionPresentation>, next_safe_actions: Array<NextSafeAction>, evidence_links: Array<string>, operation_links: Array<string>, };

export type ConsoleActionInvocation = { application_session_id: string, invocation_capability: string, operation_id: string, expected_revisions: CanonicalRevisions, arguments: Record<string, unknown>, };

/** §8.3's information architecture. Generated; the daemon serves the same list. */
export const CONSOLE_NAVIGATION = {
 GLOBAL: [
  { label: "Overview", children: [] },
  { label: "Projects", children: [] },
  { label: "Inbox", children: [] },
  { label: "Doctor", children: [] },
  { label: "Extensions", children: [] },
  { label: "Settings", children: [] }
 ],
 PROJECT: [
  { label: "Overview", children: [] },
  { label: "Work", children: ["Tasks", "Packs"] },
  { label: "Resources", children: ["Resources", "Observation"] },
  { label: "Baselines", children: ["Baselines", "Publications"] },
  { label: "Activity", children: [] },
  { label: "Providers", children: [] },
  { label: "Extensions", children: ["Extensions", "Tools"] }
 ],
 CHANGE: [
  { label: "Summary", children: [] },
  { label: "Intent", children: [] },
  { label: "Scope", children: [] },
  { label: "Revisions", children: [] },
  { label: "Impact", children: [] },
  { label: "Representations", children: [] },
  { label: "Evidence", children: [] },
  { label: "Assessments", children: [] },
  { label: "Review", children: [] },
  { label: "Decisions", children: [] },
  { label: "Gates", children: [] },
  { label: "Promotion", children: [] },
  { label: "Receipts", children: [] },
  { label: "Recovery", children: [] }
 ],
 BASELINE: [
  { label: "Summary", children: [] },
  { label: "State root", children: [] },
  { label: "Evidence root", children: [] },
  { label: "Coverage", children: [] },
  { label: "Lineage", children: [] },
  { label: "Composition", children: [] },
  { label: "Recoverability", children: [] },
  { label: "Receipts", children: [] },
  { label: "Publications", children: [] }
 ],
} as const;
