// Generates src/theme/tokens.css from src/theme/tokens.json.
// Run with `npm run tokens`. Never edit the generated CSS by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "src/theme/tokens.json"), "utf8"));

const variable = (name) => `--${name.replaceAll(".", "-")}`;
const block = (entries, indent) =>
  Object.entries(entries)
    .map(([name, value]) => `${indent}${variable(name)}: ${value};`)
    .join("\n");

const css = `/* @generated by scripts/generate-theme.mjs from src/theme/tokens.json. Do not edit by hand. */

:root {
  color-scheme: light;
${block(tokens.scale, "  ")}
${block(tokens.light, "  ")}
}

:root[data-theme="dark"] {
  color-scheme: dark;
${block(tokens.dark, "  ")}
}

@media (prefers-color-scheme: dark) {
  :root[data-theme="system"] {
    color-scheme: dark;
${block(tokens.dark, "    ")}
  }
}
`;

writeFileSync(resolve(root, "src/theme/tokens.css"), css);
console.log("src/theme/tokens.css regenerated");
