//! Frozen evidence for the extension contract's format revision.
//!
//! These expected values are inputs to the test, never generated by the code
//! under test: the canonical forms were produced by an independent
//! implementation of `proto/specs/canonicalization.md`. A mismatch is a contract
//! regression unless the original vector is independently proven invalid.
//!
//! The manifest/contribution vectors and the catalog vectors are deliberately
//! independent of one another. The catalog fixture is a signed targets document,
//! frozen to prove canonical signing and verification; it does not describe the
//! manifest fixture, and nothing here should be read as linking the two.

use draft_extension_contract::{
    canonical_json,
    catalog::{self, CatalogKey, RoleSpec, SignedEnvelope},
    package, ContributionPayload, ExtensionContributionKind, ExtensionManifest,
    ExtensionPermission, FormatError, TargetsMetadata, FORMAT_REVISION,
};
use serde_json::Value;
use std::collections::BTreeMap;

const MANIFEST: &[u8] = include_bytes!("fixtures/v1/manifest.json");
const CLASSIFICATION: &[u8] = include_bytes!("fixtures/v1/classification.json");
const VERIFICATION: &[u8] = include_bytes!("fixtures/v1/verification.json");
const INVALID_VERIFICATION: &[u8] = include_bytes!("fixtures/v1/invalid-verification.json");
const RESULT_SCHEMA: &[u8] = include_bytes!("fixtures/v1/result.schema.json");
const CANONICAL_INPUT: &[u8] = include_bytes!("fixtures/v1/canonical-input.json");
const CATALOG: &[u8] = include_bytes!("fixtures/v1/catalog-targets.json");
const SIGNED_CATALOG: &[u8] = include_bytes!("fixtures/v1/signed-catalog-targets.json");

fn vectors() -> Value {
    serde_json::from_str(include_str!("fixtures/v1/vectors.json")).unwrap()
}

#[test]
fn manifest_decodes_validates_and_keeps_its_exact_canonical_form() {
    let expected = vectors();
    let manifest: ExtensionManifest = serde_json::from_slice(MANIFEST).unwrap();
    manifest.validate_shape("0.3.4").unwrap();
    assert_eq!(
        canonical_json(&serde_json::to_value(manifest).unwrap()),
        expected["manifest_canonical"].as_str().unwrap()
    );
}

#[test]
fn contribution_payloads_keep_their_acceptance_boundary() {
    let expected = vectors();

    let classification = ContributionPayload::decode(
        ExtensionContributionKind::ResourceClassification,
        CLASSIFICATION,
    )
    .unwrap();
    classification.validate().unwrap();
    assert_eq!(
        canonical_json(&serde_json::from_slice(CLASSIFICATION).unwrap()),
        expected["classification_canonical"].as_str().unwrap()
    );
    // A classification mints exactly one contributed identifier, and it names
    // the publisher that owns it.
    assert_eq!(
        classification
            .contributed_ids()
            .iter()
            .map(|id| id.qualified())
            .collect::<Vec<_>>(),
        ["example.vector/document"]
    );

    let verification =
        ContributionPayload::decode(ExtensionContributionKind::Verification, VERIFICATION).unwrap();
    verification.validate().unwrap();
    assert_eq!(
        canonical_json(&serde_json::from_slice(VERIFICATION).unwrap()),
        expected["verification_canonical"].as_str().unwrap()
    );
    // The check is command-backed, so it needs the execute permission and
    // declares exactly one operation with one request/response contract pair.
    assert_eq!(
        verification.required_permissions(),
        vec![ExtensionPermission::ProcessExecute]
    );
    assert_eq!(verification.operations().len(), 1);
    assert_eq!(verification.schema_refs().len(), 2);

    // Declaring no check at all decodes, then fails validation: a package that
    // installed this way would report healthy while verifying nothing.
    let invalid = ContributionPayload::decode(
        ExtensionContributionKind::Verification,
        INVALID_VERIFICATION,
    )
    .unwrap();
    assert!(matches!(invalid.validate(), Err(FormatError::Identity(_))));

    // A payload is decoded by its declared kind, never by sniffing its shape.
    assert!(matches!(
        ContributionPayload::decode(ExtensionContributionKind::Comparison, CLASSIFICATION),
        Err(FormatError::Encoding(_))
    ));
}

#[test]
fn a_packaged_schema_is_bounded_and_non_networked() {
    let document = draft_extension_contract::schema::validate_schema_bytes(
        RESULT_SCHEMA,
        "fixture result schema",
    )
    .unwrap();
    assert_eq!(document["title"], "Vector result");
    assert!(package::is_admissible_package_path(
        "schemas/result.schema.json"
    ));
    // A schema is admissible only under its own namespace and only when it
    // names itself as one.
    assert!(!package::is_admissible_package_path("schemas/result.json"));
    assert!(!package::is_admissible_package_path(
        "docs/result.schema.json"
    ));
}

#[test]
fn canonical_json_bytes_are_frozen() {
    let expected = vectors();
    let input: Value = serde_json::from_slice(CANONICAL_INPUT).unwrap();
    assert_eq!(
        canonical_json(&input).as_bytes(),
        expected["canonical_json"].as_str().unwrap().as_bytes()
    );
}

#[test]
fn package_stream_and_digest_are_frozen() {
    let expected = vectors();
    let mut entries = vec![
        ("extension.json".to_string(), MANIFEST.to_vec()),
        (
            "contributions/classification.json".to_string(),
            CLASSIFICATION.to_vec(),
        ),
        (
            "contributions/verification.json".to_string(),
            VERIFICATION.to_vec(),
        ),
        (
            "schemas/result.schema.json".to_string(),
            RESULT_SCHEMA.to_vec(),
        ),
        ("docs/readme.md".to_string(), b"# Vector\n".to_vec()),
        ("LICENSE.txt".to_string(), b"Apache-2.0\n".to_vec()),
    ];
    let stream = package::content_stream(&mut entries).unwrap();
    assert_eq!(
        stream.len() as u64,
        expected["package_stream_length"].as_u64().unwrap()
    );
    assert_eq!(
        package::digest(&stream),
        expected["package_digest"].as_str().unwrap()
    );
    assert!(package::is_admissible_package_path(
        "contributions/classification.json"
    ));
    assert!(!package::is_admissible_package_path("bin/extension"));
}

#[test]
fn catalog_signable_bytes_and_fixed_signature_are_frozen() {
    let expected = vectors();
    let catalog: TargetsMetadata = serde_json::from_slice(CATALOG).unwrap();
    let signable = catalog::signable_bytes(&catalog).unwrap();
    assert_eq!(
        signable,
        expected["catalog_signable"].as_str().unwrap().as_bytes()
    );

    let envelope: SignedEnvelope<TargetsMetadata> = serde_json::from_slice(SIGNED_CATALOG).unwrap();
    assert_eq!(envelope.signable_bytes().unwrap(), signable);
    let public_key = expected["public_key"].as_str().unwrap();
    let signature = expected["signature"].as_str().unwrap();
    assert!(catalog::verify_signature(public_key, &signable, signature).unwrap());

    let mut modified = signable.clone();
    modified[0] ^= 1;
    assert!(!catalog::verify_signature(public_key, &modified, signature).unwrap());

    let keys = BTreeMap::from([(
        "vector-key".to_string(),
        CatalogKey {
            algorithm: catalog::SIGNATURE_ALGORITHM.into(),
            public_key: public_key.into(),
        },
    )]);
    let role = RoleSpec {
        key_ids: vec!["vector-key".into()],
        threshold: 1,
    };
    catalog::verify_envelope(&envelope, &role, &keys, &[]).unwrap();

    let mut tampered = envelope;
    tampered.signed.version += 1;
    assert!(matches!(
        catalog::verify_envelope(&tampered, &role, &keys, &[]),
        Err(FormatError::Signature(_))
    ));
}

#[test]
fn compatibility_and_format_revision_are_frozen() {
    let expected = vectors();
    assert_eq!(
        FORMAT_REVISION as u64,
        expected["format_revision"].as_u64().unwrap()
    );
    assert_eq!(FORMAT_REVISION, 1);
    for outcome in expected["compatibility"].as_array().unwrap() {
        assert_eq!(
            draft_extension_contract::draft_api_compatible(
                outcome["requirement"].as_str().unwrap(),
                outcome["api_version"].as_str().unwrap()
            ),
            outcome["supported"].as_bool().unwrap()
        );
    }
}
